---
- name: "anyenv root"
  git:
    repo: https://github.com/riywo/anyenv
    dest: "{{ anyenv_home_dir }}/.anyenv"
    update: "{{ git_update }}"
    depth: "{{ git_depth }}"
- name: "anyenv path in .bashrc"
  lineinfile:
    dest: "{{ anyenv_home_dir }}/.bashrc"
    regexp: 'anyenv/bin'
    line: 'export PATH="$HOME/.anyenv/bin:$PATH"'
- name: "anyenv init in .bashrc"
  lineinfile:
    dest: "{{ anyenv_home_dir }}/.bashrc"
    regexp: 'anyenv init'
    line: 'eval "$(anyenv init - --no-rehash)"'
- name: "anyenv plugins"
  git:
    repo: "{{ item }}"
    dest: "{{ anyenv_home_dir }}/.anyenv/plugins/{{ item | basename }}"
    update: "{{ git_update }}"
    depth: "{{ git_depth }}"
  with_items: "{{ anyenv_plugins }}"
- name: "rbenv"
  git:
    repo: https://github.com/rbenv/rbenv
    dest: "{{ anyenv_home_dir }}/.anyenv/envs/rbenv"
    update: "{{ git_update }}"
    depth: "{{ git_depth }}"
- name: "rbenv plugins"
  git:
    repo: "{{ item }}"
    dest: "{{ anyenv_home_dir }}/.anyenv/envs/rbenv/plugins/{{ item | basename }}"
    update: "{{ git_update }}"
    depth: "{{ git_depth }}"
  with_items: "{{ rbenv_plugins }}"
